Update abaqus documentation
ACRC/HPC-community-docs pull request #20
Opened 2023-07-24 15:03 UTC by LKedward

- Fix some old broken links to the registration form
  - Replace with simple text to speak to supervisor about Abaqus registration
- Update the job submission script templates to include the new `--account` field with explanation
- Add short text and link to submitting jobs using Abaci instead

@jcwomack

2023-07-27 10:14 UTC, jcwomack requested changes
Thanks for this update @LKedward. It all looks good. I've checked the built HTML docs and everything seems in order. 

I've made a couple of very minor suggestions for changes to the text. Once these are made, I'll be happy to merge this PR 🙂

Thanks again!

2023-07-27 10:14 UTC, jcwomack commented on source/engineering/abaqus/index.md
> +Before using Abaqus at the university, you must first register for an Abaqus license -
```suggestion
Before using Abaqus at the university, you must first register for an Abaqus license -
```

Suggest removing double space after hyphen, as this leads to a line-break in rendered text.

2023-07-27 13:00 UTC, LKedward commented
Thanks for reviewing! Suggestions applied 👍

2023-08-01 08:59 UTC, jcwomack approved these changes

2023-08-01 09:00 UTC, merged